name: 07-03-context 

on: 
  workflow_dispatch:
    inputs: 
      myinput:
        type: string 
        description: enter your name
        #default: vijay


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Display Event Information 
       run: echo helloworld ${{ inputs.myinput}}